### ISSUE TITLE
Add / Remove text fields dynamically

### ISSUE THREAD

**Issue by ecvilibrium** [buttflattery/yii2-formwizard#10]
Hi It is possible to add and remove text fields dynamically by click button (Add/remove), (+ / -) 
![image](https://user-images.githubusercontent.com/24956066/52122710-85664780-262c-11e9-8769-ca0fd5990032.png)

**Comment by buttflattery** [comment]
Umm...No, currently it does not support it i am working on an update which includes this functionality as it would need to validate the fields before moving on if those fields are required, so it requires a bit more time and testing before i can push it to the repo, i will be trying my best on this weekend to finish it and make it live till Monday. will update you here when i am done.

**Comment by buttflattery** [comment]
A new feature has been added to the repo as `Tabular Steps` which addresses this issue, you can see the readme or go to the wiki [here](https://github.com/buttflattery/yii2-formwizard/wiki/Tabular-Steps-(New-Feature)) . Hope it solves your issue @ecvilibrium

**Comment by ecvilibrium** [comment]
Thx!!! for your work!!!

**Comment by buttflattery** [comment]
you are welcome
