### ISSUE TITLE
Repeat Steps

### ISSUE THREAD

**Issue by racielbd** [buttflattery/yii2-formwizard#11]
Hi
I'm trying to make a step repeat several times and I can not find a way to do it in this repository ...
Could you tell me if there is a possibility that it could be done through an option for example repeat step (boolean) and in the sumit would pass to the model an array of that model... I'ts just an idea...

thanks...

**Comment by buttflattery** [comment]
can you provide more detail about what you are trying to achieve, and what you actually mean by repeat the steps? are you looking to populate same set of inputs in several steps?

**Comment by racielbd** [comment]
At this time the extension develops a wizard in one way with 1 or more models, but what happens when one of those models is an array... let's say we have the client and the contact model where the wizard form would consist of 2 steps 1 for the client and another one for the contact but in case of being several contacts for the same client it would be necessary an option that make a loop on the second step... to introduce the others contacts and perhaps to place some buttons of next and back of that model... apart from the original form and in the widget it could be something like that

`use buttflattery\formwizard\FormWizard;
echo FormWizard::widget([
    'steps'=>[
        [
            'model'=>$clientModel,
            'title'=>'My Clients',
            'description'=>'Add your client',
            'formInfoText'=>'Fill all fields'
        ],
        [
            'model'=> $contactModel,
            'title'=>'TheConctacts',
            'loop'=> true,
            'max' => 4.
            'min'=> 1 // or 0
            'description'=>'Add the clients contacts',
            'formInfoText'=>'Fill all fields'
        ],
    ]
]);`

Great extension by the way and thanks for your attention

**Comment by buttflattery** [comment]
Hello @racielbd i think what you are looking for is something i am already working on [SEE THIS ISSUE](https://github.com/buttflattery/yii2-formwizard/issues/10) initially i thought it might not take long but due to some priorities to other projects, i am not able to add the update yet.

**Comment by buttflattery** [comment]
Hello @racielbd  a new feature **Tabular Step** has been added you can pull to use the feature you read about it in the ReadMe or the wiki [here](https://github.com/buttflattery/yii2-formwizard/wiki/Tabular-Steps-(New-Feature))
