### ISSUE TITLE
how to set hint?

### ISSUE THREAD

**Issue by wa1kb0y** [buttflattery/yii2-formwizard#12]
Thank you for great extension, can u explain pls, how to set hint() for input group?

**Comment by buttflattery** [comment]
@wa1kb0y that is a good catch i must say, as it wasnt added into the code base yet, just give me a few hours and i will update you once i push it to live repo and you can pull the changes via composer, most probably tomorrow morning. Thanks for adding an issue here

**Comment by buttflattery** [comment]
@wa1kb0y there is already a method provided in YII2 for the hints, i just checked and you can provide hints for the ActiveRecord fields in the respective models and Yii will automatically add those hints when populating the fields for example you have a model named `Products` and you are displaying the fields in a step and want to show a hint for product `name` attribute as `"Names should not be in Capslock"`. 

What you should do is override the `attributeHints()` inside the `Product` model, just remember to merge parent attributes using `array_merge` and return the hints see below 

```
public function attributeHints()
{
    $hints = parent::attributeHints();
    return array_merge(
        $hints, [
            'name' => 'Names should not be in Capslock',
        ]
    );
}
```

Now go and refresh your formwizard the hint will be visible along the desired field

**Comment by buttflattery** [comment]
If this doesnot solve the problem you can add your code to address the specific issue you are having so we can figure it out.

**Comment by wa1kb0y** [comment]
it works, thank you, but what if I need different hints for different forms in the application, for example one on frontend and different one on backend.
maybe you can add something like this:
```php
```

**Comment by buttflattery** [comment]
Yes, the reason I provided the above code so that you could get it working right away as I was in office at that time, I would surely add the updated and leave a message here you can then pull from the composer. @wa1kb0y

**Comment by wa1kb0y** [comment]
@buttflattery great, thank you for help

**Comment by buttflattery** [comment]
@wa1kb0y you can run `composer update` now and pull the latest code, you can provide the `hint` option in the `fieldConfig` under the specific field like below

```
'fieldConfig' => [
    'only' => ['title', 'store_url'],
    'title' => [
        'hint' => 'My Hint Text',
        'containerOptions' => [
            'class' => 'form-group',
        ],
        'inputOptions' => [
            'placeholder' => 'My Text',
        ]
    ]
]
```

You can close the issue once you have tested it, i have updated the docs and the change log too, so taht you can see the actual changes and understand the usage in all scenarios.

**Comment by wa1kb0y** [comment]
it works, thanks a lot!
