### ISSUE TITLE
How to get data from previous step?

### ISSUE THREAD

**Issue by wa1kb0y** [buttflattery/yii2-formwizard#16]
Is it possible to know what the user was entered on first step to use it for some dependance on 2nd step? Maybe you can add something to fill model via ajax after clicking "next" and use this filled data to build next step.

**Comment by buttflattery** [comment]
@wa1kb0y i am not getting the idea behind it. 
i get the part 

- Is it possible to know what the user was entered on first step

but not

- to use it for some dependance on 2nd step?

are you saying that you want to do something at your end by determining the data entered for the first step or want the formwizard to integrate this functionality?

Also, the steps are pre-populated on server-side, and all of the steps fall into a single `ActiveForm` so if there is something like a `DepDrop` used in the first step on which the dropdown in the second select should reflect the changes then you dont have to do anything for that. just configure them as you normally do.

Or if you are pointing to something else please elaborate.

**Comment by wa1kb0y** [comment]
@buttflattery thank you, i dont thought about `depProp`, its solved my issue.

Maybe will helpful to somebody, how to configure it to use with `kartik-v/yii2-widget-depdrop`:
```php
'fieldConfig' => [
...
    'sub_category_id' => [
        'widget' => DepDrop::classname(),
        'options' => [
            'pluginOptions' => [
                'depends' => ['parent-select-id'],
                'placeholder' => 'Select...',
                'url' => Url::to(['/site/get-categories'])
            ]
        ]
    ],
...
]
```
