### ISSUE TITLE
Upload multiple images with kartik-v file input extension

### ISSUE THREAD

**Issue by chirie** [buttflattery/yii2-formwizard#2]
Hi, your extension works fine. I am so glad you saved me a lot of hustle when creating my app. However, I encountered a problem whereby I am unable to upload multiple images by making the form field accept an array; i.e. an image field with the field name of <image> will have to be <image[]> so as to accept multiple uploads which does not work in this case. This is part of my code for the _form.php view:

```
[
    'model'=>$imageModel,
    'title'=>'Images',
    'description'=>'Give us the details of the list',
    'formInfoText'=>'Fill all required fields',
    'fieldConfig' => [
        'only' => ['image[]'],
        'image[]' => [
            'widget' => FileInput::classname(),
            'options' =>[
                'options' => [
                    'multiple' => true,
                    'accept' => 'image/*',
                    'pluginOptions' => [
                        'showCaption' => false,
                        'showRemove' => false,
                        'showUpload' => false,
                        'browseClass' => 'btn btn-primary btn-block',
                        'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
                        'browseLabel' =>  'Attach Listing Images',
                        'allowedFileExtensions' => ['jpg','gif','png'],
                        'overwriteInitial' => false
                    ],
                ],
            ],
        ]
    ]
],

```
Kindly assist where possible;

**Comment by chirie** [comment]
Hi, thanks for taking care of this. I have implemented that part and it is working fine as I expected. Now, I have another problem still on the same image. Now, when I submit the form, I get the images model as blank and instead get an array of $_FILES underneath it is an array of images. And I am at a loss of how to handle that. Here is the submitted form details to the server:

`$_POST = [
    '_csrf-backend' => '_ioSvkoWdYDTEG_L4AHgnyQSEe7pZOqEWwQfPANPbM2uGkbIKHo8y5ZAGriqT4XsQCBkl5sOnvweT31wUx01kg==',
    'Listing' => [
        'listing_title' => 'tyguhijokpl[',
        'country' => '2',
        'states' => '4',
        'area_id' => '1537',
        'physical_address' => 'yghbunjikmol,',
        'neighborhood' => 'gvybhunjimko,l',
        'address' => 'Dandora phase 4, Nairobi, Kenya',
        'latitude' => '-1.2423923',
        'longitude' => '36.90438449999999',
    ],
    'Property' => [
        'property_category' => '1',
        'sub_category_id' => '2',
        'currency_id' => '1',
        'price' => '897465123',
        'property_features' => [
            '1',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
        ],
    ],
    'ListingImages' => [
        'image' => [
            '',
        ],
    ],
];

$_FILES = [
    'ListingImages' => [
        'name' => [
            'image' => [
                'coins-1015125_1920.jpg',
                'computer-768608_1920.jpg',
                'content-is-king-1132259_1920.jpg',
                'content-marketing.jpg',
                'contentpyramid.png',
                'cup-of-coffee-1280537_1920.jpg',
                'ecommerce-3546296_1920.jpg',
                'email-3249062_1280.png',
            ],
        ],
        'type' => [
            'image' => [
                'image/jpeg',
                'image/jpeg',
                'image/jpeg',
                'image/jpeg',
                'image/png',
                'image/jpeg',
                'image/jpeg',
                'image/png',
            ],
        ],
        'tmp_name' => [
            'image' => [
                'C:\\xampp\\tmp\\php8AF1.tmp',
                'C:\\xampp\\tmp\\php8B02.tmp',
                'C:\\xampp\\tmp\\php8B03.tmp',
                'C:\\xampp\\tmp\\php8B23.tmp',
                'C:\\xampp\\tmp\\php8B34.tmp',
                'C:\\xampp\\tmp\\php8B35.tmp',
                'C:\\xampp\\tmp\\php8B46.tmp',
                'C:\\xampp\\tmp\\php8B47.tmp',
            ],
        ],
        'error' => [
            'image' => [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
        ],
        'size' => [
            'image' => [
                364796,
                275881,
                310313,
                301511,
                119458,
                508911,
                219479,
                242737,
            ],
        ],
    ],
];`

Can I get help with this or this is an issue with my code setup? Thanks once again.

**Comment by chirie** [comment]
I found out my problem and now the system is working fine. Please disregard the last comment.

**Comment by buttflattery** [comment]
do update the extension i have added a few bug fixes see this [issue](https://github.com/buttflattery/yii2-formwizard/issues/5) @chirie
