### ISSUE TITLE
why call resetForm?

### ISSUE THREAD

**Issue by SuiFeng** [buttflattery/yii2-formwizard#28]
$(form).yiiActiveForm("resetForm");

**Comment by buttflattery** [comment]
That is used to clear the error labels for the steps that are yet to be viewed or filled by the user. as the activefrom validation is triggered for the whole form. what problem are you having? @SuiFeng

**Comment by buttflattery** [comment]
for clearing the validation messages for those step fields that are yet to be filled in by the user. What problem are you having?. @SuiFeng
