### ISSUE TITLE
Hidden fields

### ISSUE THREAD

**Issue by thomassb** [buttflattery/yii2-formwizard#3]
We could do with hidden fields on the form

 \buttflattery\formwizard\FormWizard ->createCustomizedField

'hidden' => function ($field, $options, $labelOptions, $label){
                return $field->hiddenInput($options)->label(false);
            }

**Comment by buttflattery** [comment]
i cant get what you are actually asking here? are you asking about how to create a hidden field input? @thomassb

**Comment by thomassb** [comment]
I don't think you have the ability to add hidden fields, the code and the documentation seems to reflect this.
I can add a push request with the new code if you want.

**Comment by buttflattery** [comment]
Yes it was missing previously, i already added it you can pull the latest in which you can add `hidden` and the `password` field too, which also wasn't supported. The docs are updated too. @thomassb

**Comment by thomassb** [comment]
Your welcome.
And thank you for updating it.

**Comment by buttflattery** [comment]
No problem @thomassb  , Thank YOU for adding the issue to improve the extension.
