### ISSUE TITLE
demo site not opening

### ISSUE THREAD

**Issue by emuthomi** [buttflattery/yii2-formwizard#37]
Your domain seems to have expired and therefore demos not available online

**Comment by buttflattery** [comment]
@emuthomi , yes I forgot to renew the domain and godaddy is not responding now, I added a note on the docs where the demo links are provided that the site will be up this weekend. You can see the complete code references on the [wiki](https://github.com/buttflattery/yii2-formwizard/wiki) meantime. 

Sorry for the inconvenience.

**Comment by buttflattery** [comment]
hello @emuthomi the demos are up and running now
