### ISSUE TITLE
Default form action on update

### ISSUE THREAD

**Issue by thomassb** [buttflattery/yii2-formwizard#4]
The default ActiveForm action is overwitten in setDefaults()

`  $this->formOptions['action'] = ArrayHelper::getValue($this->formOptions, 'action', Url::to(['/' . Yii::$app->controller->id . '/' . Yii::$app->controller->action->id]));`

This causes problems when the form is used to update an existing model, action should only be changed if it has been specified it in widget options.

**Comment by buttflattery** [comment]
@thomassb the form action attribute if not specified will be set to the current `controller` and the `action` where the formwizard is loaded, even if you are updating the existing model it would do the same, means if it does not find the `action` option under the `formOptions`.

 I don't quite understand the scenario that you are referring to. Can you please explain.

**Comment by thomassb** [comment]
@buttflattery If you use the widget to update an existing modal then the 'id' is not specified in the action url.
e.g.
Form Wizard action URL
web/policy/update
Correct URL
web/policy/update?id=1

Html::beginForm takes care of this for you so there is no need to manually set the form action.


` //set default action of the form user specified action if need
        if (isset($this->formOptions['action'])) {
            $this->formOptions['action'] = $this->formOptions['action'];
        }`

**Comment by buttflattery** [comment]
Ahh i get it , yes you are right we dont need to set it, i would remove that line and update here after i push to the repo. Then you can pull the latest changes.

**Comment by buttflattery** [comment]
@thomassb  i just updated it you can pull the changes and close the issue if it is all good. Feel free to add another issue if you run into any problems.

**Comment by buttflattery** [comment]
@thomassb do update composer, see this [issue](https://github.com/buttflattery/yii2-formwizard/issues/5) for details.
