### ISSUE TITLE
Tabular Input

### ISSUE THREAD

**Issue by chandee77** [buttflattery/yii2-formwizard#40]
Tabular data can not be collected from the backed(controller) using the way specified by Yii2 tabular data collection. to achieve this in yii2 I need to use "Model::loadMultiple" in my controller for that I need to declare my model as array and initialize it.then the beauty of fronted is lost (front end is not dynamic).and if I pass a array with single object I can catch only one object from controller. how can I solve this.can you share your sample controller which relevant to given example in tabular form

**Comment by chandee77** [comment]
Tabular data can not be collected from the backed(controller) using the way specified by Yii2 tabular data collection. to achieve this in yii2 I need to use "Model::loadMultiple" in my controller for that I need to declare my model as array and initialize it.then the beauty of fronted is lost (front end is not dynamic).and if I pass a array with single object I can catch only one object from controller. how can I solve this.can you share your sample controller which relevant to given example in tabular form

**Comment by buttflattery** [comment]
@chandee77 you havent understood the concept yet for the tabular inputs and saving them into the form please see this answer on stackoverflow 
https://stackoverflow.com/questions/57713074/tabular-form-in-yii2-formwizard-for-dynamic-input/57717099#57717099
