### ISSUE TITLE
Add possibility to group fields horizontally

### ISSUE THREAD

**Issue by valieand** [buttflattery/yii2-formwizard#43]
see subj

**Comment by buttflattery** [comment]
@valieand Are you referring to **Group Fields** feature https://yii2plugins.omaraslam.com/formwizard/group-fields and want to align the fields horizontally ?
If yes? then you can simply use the `form-inline` class within the `formOptions` like below

```
'formOptions'=>[
        'options'=>[
            'class'=>'form-inline'
        ]
    ],
```

**Comment by buttflattery** [comment]
i would be closing the issue, if there is something else you are trying to do please elaborate.
