### ISSUE TITLE
Need help on FORM widget Yii2

### ISSUE THREAD

**Issue by girishcp** [buttflattery/yii2-formwizard#46]
I am using your plugin Yii2 form widget and its really cool but i want to implement more functionality on this widget like based on the selection of fields (select2) from 1st step then the other steps will be visible. Is it possible?

**Comment by buttflattery** [comment]
Not sure if you are only trying to show/hide or navigate, but you might have to look into the api for the smartwizard plugin, i think there is a `goToStep()` function inside the `smartWizard.js` library which can help you do this, but you might have to do alot customization by forking the repo and do your customization, as it does not have any such functionality built-in also the navigation of the steps  is dependent on the next and previous buttons which have no option to be disabled, so you would have to try it on your own forked repo. @girishcp
