### ISSUE TITLE
DISABLE STEP VALIDATION

### ISSUE THREAD

**Issue by ritacionfoli** [buttflattery/yii2-formwizard#47]
Hi, is there a way to disable the validation of a step and not the whole form?
Thx

**Comment by buttflattery** [comment]
umm..... as far as i remember the widget depends on the model validation rules to decide if you have to validate or not, if inputs listed inside the step are not mandatory inside the model rules your step fields wont be validated. Can you explain your scenario? @ritacionfoli

**Comment by ritacionfoli** [comment]
I've the main model in the first 2 steps. In the last 3 there are 3 differents models related to the main one. Since the relation is 0 to many, how can I skip the step if I don't have to insert a record?

**Comment by buttflattery** [comment]
i might have to test once, can you provide your schema that you are trying to use with the formwizard @ritacionfoli

**Comment by ritacionfoli** [comment]
it's an update form of a user profile
1 step: form with main model (user);
2 step: form with model->1relation (address);
3 step: tabular step with model->2relation (publications). I need to skip this step, because an user may not have published books.

**Comment by buttflattery** [comment]
Hmm, i get it now what you are talking about, what i understand that you are asking if the widget could automatically skip a complete model/step depending on the nature of that model relation to the earlier step models, at the same time without changing the validation rules for the step model. 

Currently i dont think it is possible as there is no default feature in the smartWizard Library which it depends on and i havent added any such feature in the widget too, but i think this is a feasable requirement and very common scenario used overall. 

So i am adding this feature on this weekend hopefully, and will update you once i am done with it.
Have a good day @ritacionfoli

**Comment by ritacionfoli** [comment]
@buttflattery thank you!

**Comment by buttflattery** [comment]
@ritacionfoli The new release has been added you can run `composer update` to update the widget to the latest `1.5.0` version and use the `isSkipable` options as described [on WIKI](https://github.com/buttflattery/yii2-formwizard/wiki/Skip-Step-Validation) , please close the issue if you dont get into any problems once you have updated and tested the new Feature.
Have a good day.

**Comment by ritacionfoli** [comment]
Great! It works...thank you!
