### ISSUE TITLE
Form layout

### ISSUE THREAD

**Issue by ritacionfoli** [buttflattery/yii2-formwizard#49]
Hi, after updating I noticed that there's a bug in the output of the form. Below is a screenshot of the problem.
![bug](https://user-images.githubusercontent.com/9607089/72242295-581a6b80-35e9-11ea-835d-a3130e2874f4.png)

**Comment by buttflattery** [comment]
@ritacionfoli i dont think it has to do anything with the recent updates this looks more like a css problem as the first input `Uomo` in NOW and BEFORE are same but not the next 2, i have updated the extension on the demo site too and i dont find any odd behavior with the css see the customized input demo here https://yii2plugins.omaraslam.com/formwizard/customize-fields 
You might have to inspect the css via dev bar inspector and see what extra classes are there which are causing them to dismantle the layout.

**Comment by ritacionfoli** [comment]
I think it depends on the loaded assets. When I load the page with the widget, the layout of the whole site is changed, in the other pages it is not. I send you the screenshots to try to make me understand.
![right_layout](https://user-images.githubusercontent.com/9607089/72253323-991e7a00-3601-11ea-886d-9180b6ffaf38.png)
![layout](https://user-images.githubusercontent.com/9607089/72253479-f0244f00-3601-11ea-9e93-402613c8655e.png)

**Comment by buttflattery** [comment]
okay, can you tell me what particular theme are you using so i can check it on my end and what classes are used on the links that are incorrectly placed when you include the widget.

I will reply back after i check and find the issue @ritacionfoli

**Comment by ritacionfoli** [comment]
It's a problem that come from bootstrap version. I'm using bootstrap3, but the widget loads assets for the version 4

**Comment by buttflattery** [comment]
if you look into registerScripts method it will always look for bootstrap4 extension first and if not found it falls back to 3 , ao if it ia loading the bs4 assets and you are using bootstrap3 then it means you have installed both of those versions you need to remove the bs4 from the composer.json of your project as it does not make sense to install both of them if you are using only one version @ritacionfoli

**Comment by ritacionfoli** [comment]
[composer.json.txt](https://github.com/buttflattery/yii2-formwizard/files/4055211/composer.json.txt)

**Comment by buttflattery** [comment]
You are using the user module `yii2-pluto`  which requires `bootstrap4` see here  https://github.com/sjaakp/yii2-pluto/blob/master/composer.json due to which you have the bootstrap4 extension installed you might need to look into its docs to use BS3 or you may have to switch to some other better rated module. @ritacionfoli

**Comment by ritacionfoli** [comment]
I've seen it. Thank you

**Comment by buttflattery** [comment]
As there are few other similar queries that are having the same situation and want to force the bootstrap version for the widget, so i am reopening this issue and would be adding the option in the new release.

**Comment by buttflattery** [comment]
@ritacionfoli i just released a new version with 2 new features, one of which include forcing bootstrap version with option simple as `"forceBsVersion"=>FormWizard::BS_3` . run `composer update` to update tot he latest version `1.6.4`.

**Comment by ritacionfoli** [comment]
@buttflattery  many thanx!!!
