### ISSUE TITLE
Keyboard navigation left and right skips validation

### ISSUE THREAD

**Issue by idowstech** [buttflattery/yii2-formwizard#5]
If we press `left` or `right` arrow key the steps validation is not performed and you can walk through the steps forward and backwards ?

**Comment by buttflattery** [comment]
Yes you are right it is the default functionality of the `smartWizard` library which has the default value for this option as `true`, and we are not using the default steps navigation for the formwizard, but the manual navigation as the default nex previous buttons used events to navigate or to deny navigation, and was not going to work with `yiiActiveForm.js` events, so i disabled those options for This Yii2 Extension and forgot to set this option as `false` by default when the plugin is initialized.

Will add a fix soon and update you can them pull the latest version.

**Comment by buttflattery** [comment]
just added the fix and published changes, you can pull now using `composer update`. @idowstech

**Comment by thomassb** [comment]
Has this not introduced a bug which means we can't navigate back through the tabs using the tab headers?

**Comment by thomassb** [comment]
On traversing back the steps on smartwizard the validation is removed from all steps forward of the step you click on. Can this be mimicked?

**Comment by buttflattery** [comment]
@thomassb i dont get the part 

> "the validation is removed from all steps forward of the step you click on" 

i just looked at the [validation-demo](http://techlaboratory.net/smartwizard/demo/validation) but could not get what you are trying to tell, can you explain.

**Comment by thomassb** [comment]
Validation is always performed when moving forward in the steps, can you not call your validation function here?

`  $("#smartwizard").on("leaveStep", function(e, anchorObject, stepNumber, stepDirection) {
 var elmForm = $("#form-step-" + stepNumber);
                if(stepDirection === 'forward' && elmForm){
            ...
                }
                return true;
            });`

**Comment by buttflattery** [comment]
@thomassb , Validation works with binding the `beforeSubmit` and `afterValidate` of  `yiiActiveForm.js` and thats where it conflicts with the `leaveStep` and i had to keep some limitations which i mentioned in my [comment](https://github.com/buttflattery/yii2-formwizard/issues/5#issuecomment-442213592), but still keeping all the options and behaviors of  `ActiveForm` validation which if enabled should always validate all those fields that are kept required at the mode level, and wither you disable the validation using `formOptions` or you should make the field safe in the model rules.

What i am trying to understand is that are you asking this in reference to the thing you asked to mimick?

**Comment by buttflattery** [comment]
The default `Next` and `Previous` buttons that are bydefault created by the plugin `smartWizard` are not used in this extension , but custom buttons instead and navigation of the steps is also custom

**Comment by thomassb** [comment]
OK I think I get it, but excuse my ignorance but why not use the default buttons and use the leave step event and validate on this?
`$("#{$wizardContainerId}").on("leaveStep", function(e, anchorObject, stepNumber, stepDirection) {

    if (stepDirection === 'forward') {
        $('#{$this->formOptions['id']}').yiiActiveForm("validate");
        if ($("#{$this->formOptions['id']}").find(".has-error").length) {
            $.formwizard.helper.shake("#{$this->formOptions['id']}");
            return false;
        }

    }
    return true;
});`

**Comment by thomassb** [comment]
Sorry was too late my brain had gone. If you use  the `laveStep` event to trigger validation and always return false. Then Yii2 `afterValidation` event to move the step along `form.smartWizard("next");`
