### ISSUE TITLE
"kartik/DepDrop" across "WizardSteps"

### ISSUE THREAD

**Issue by victoraguilar93** [buttflattery/yii2-formwizard#51]
Hi

Basically I have a step where I select from a select2 an item and in the next step (STEP_TYPE_TABULAR) I need to load a dropdownlist, data from a relationship in the database.

table1: id, name(select2 on step1)
table2: id, name, id_table1(DepDrop as select2 on step2 where id_table1 comes from field on step1)

but I don't know how to access the value stored in the select2 of step1, to give it a parameter in step2.

plugins used: select2, preferably DepDrop; both of de kartik

I would greatly appreciate if you can help me solve my problem.

**Comment by buttflattery** [comment]
this is more like a question for stackoverflow as it has nothing to do with the formwizard widget itself and is more about select2, the steps have nothing but html and there is a single form for the whole wizard and the select2 and DepDrop both will work normally as in any other form you have and will update on selection even if the depdrop is in another step
