### ISSUE TITLE
Custom items in single Wizard-step

### ISSUE THREAD

**Issue by victoraguilar93** [buttflattery/yii2-formwizard#52]
Hi

I would like to know if it is possible to add custom items to a specific Step.

for example:

1. step1: car_model: with basic information about the car.

2. step2:

- type => tabular

- model => car_brands_model: with select2 for select brand.

**No Tabular items:**

- [ ] If the brand does not exist, there is a button to open a modal with Form in popup to add the brand.
- [ ] A button to keep the information incomplete and complete it later.

3. step3: car_owner_model.

4. step4

- [ ] Detailview with summary informacion. Save or delete data

Summary: Step2 has custom elements that I would like to know how you can add

Tknx

**Comment by buttflattery** [comment]
you should go through the wiki docs https://github.com/buttflattery/yii2-formwizard/wiki ,i dont think there is anything here you cannot do as far as i understood from your post.

**Comment by victoraguilar93** [comment]
applying the same documentation theory, but in the specific step that I want to add the items, it does not cause any effect, it can only be added in a general way to the whole form but that is not what I try to do

![image](https://user-images.githubusercontent.com/18744906/73011493-f1136880-3dd9-11ea-8231-a42d67605966.png)


![image](https://user-images.githubusercontent.com/18744906/73011529-038da200-3dda-11ea-927b-c997c64edea5.png)

**Comment by buttflattery** [comment]
are you trying to use the tabular steps? by using a custom button ? is that what you are saying? You should rather use the tabular steps if you want to use the Add row feature. See demo for [Tabular Steps](https://yii2plugins.omaraslam.com/formwizard/tabular-step)
