### ISSUE TITLE
I can't personalize my fields

### ISSUE THREAD

**Issue by hilmata** [buttflattery/yii2-formwizard#54]
Hi, I am using the buttflattery \ formwizard \ FormWizard plugin to design my form and I notice that the fields that I customize are not displayed. Here is my code : 

` <?=
                                        FormWizard::widget([
                                            'formOptions' => [
                                                'id' => 'my_form_ajax',
                                                'enableClientValidation' => true,
                                                'enableAjaxValidation' => false,
                                            ],
                                            'theme' => FormWizard::THEME_DOTS,
                                            'enablePreview' => true,
                                            'classListGroup' => 'list-group',
                                            'classListGroupHeading' => 'list-group-heading',
                                            'classListGroupItem' => 'list-group-item-info',
                                            'classListGroupBadge' => 'danger',
                                            'steps' => [
//
                                                [
                                                    'model' => $model,
                                                    'title' => 'Identité',
                                                    'description' => 'identité du membre',
                                                    'formInfoText' => 'Renseignez l\'identité du membre',
                                                    'fieldConfig' => [
                                                        'only' => [
                                                            'BASE_ID',
                                                            'MEMBRE_NOM',
                                                            'MEMBRE_PRENOM',
                                                            'MEMBRE_SEXE' => [
                                                                'options' => [
                                                                    'type' => 'dropdown',
                                                                    'itemsList' => ['M' => 'Masculin', 'F' => 'Féminin'],
                                                                    'prompt' => 'Sélectionnez le sexe',
                                                                ],
                                                            ],
                                                            'MEMBRE_DATE_DE_NAISSANCE' => [
                                                                'widget' => DatePicker::class,
                                                                'options' => [
                                                                    'language' => 'es',
                                                                    'readonly' => true,
                                                                    'pluginOptions' => [
                                                                        'autoclose' => true,
                                                                        'format' => 'dd/mm/yyyy',
                                                                        'todayHighlight' => true,
                                                                    ]
                                                                ]
                                                            ],
                                                            'MEMBRE_LIEU_DE_NAISSANCE',
                                                            'MEMBRE_PROFESSION',
                                                            'MEMBRE_CONTACT',
                                                        ], // only these field will be added in the step, rest all will be hidden/ignored.
                                                    ]
                                                ],
                                                [
                                                    'model' => $model,
                                                    'title' => 'Sacrements',
                                                    'description' => 'Sacrements reçus par le membre',
                                                    'formInfoText' => 'Renseignez les sacrements reçus par le membre',
                                                    'fieldConfig' => [
                                                        'only' => [
                                                            'MEMBRE_DATE_DE_BAPTEME',
                                                            'MEMBRE_LIEU_DE_BAPTEME',
                                                            'MEMBRE_DATE_DE_COMMUNION',
                                                            'MEMBRE_LIEU_DE_COMMUNION',
                                                            'MEMBRE_DATE_DE_CONFIRMATION',
                                                            'MEMBRE_LIEU_DE_CONFIRMATION',
                                                            'MEMBRE_DATE_DE_MARIAGE',
                                                            'MEMBRE_LIEU_DE_MARIAGE',
                                                        ], // only these field will be added in the step, rest all will be hidden/ignored.
                                                    ]
                                                ],
                                                [
                                                    'model' => $model,
                                                    'title' => 'A propos du Sacré-Coeur',
                                                    'description' => 'Cérémonies reçus par le membre',
                                                    'formInfoText' => 'Renseignez les cérémonies reçus par le membre',
                                                    'fieldConfig' => [
                                                        'only' => [
                                                            'MEMBRE_DATE_INTRONISATION',
                                                            'MEMBRE_DATE_ADMISSION_SOLLENELLE',
                                                        ], // only these field will be added in the step, rest all will be hidden/ignored.
                                                    ]
                                                ],
                                                [
                                                    'model' => $model,
                                                    'title' => 'Associations',
                                                    'description' => 'Autres associations',
                                                    'formInfoText' => 'Renseignez les autres associations dans lesquelles le membre est actif',
                                                    'fieldConfig' => [
                                                        'only' => [
                                                            'MEMBRE_ASSOCIATION1',
                                                            'MEMBRE_ROLE_ASSOCIATION1',
                                                            'MEMBRE_ASSOCIATION2',
                                                            'MEMBRE_ROLE_ASSOCIATION2',
                                                        ], // only these field will be added in the step, rest all will be hidden/ignored.
                                                    ]
                                                ],
                                                [
                                                    'model' => $model,
                                                    'title' => 'Divers',
                                                    'description' => 'Autres informations',
                                                    'formInfoText' => 'Renseignez les autres informations',
                                                    'fieldConfig' => [
                                                        'only' => [
                                                            'MEMBRE_MOTIF_ADHESION',
                                                            'MEMBRE_OBJECTIFS_A_COURS_TERME',
                                                            'MEMBRE_OBJECTIFS_A_LONG_TERME',
                                                            'MEMBRE_ROLE_ASSOCIATION2',
                                                            'MEMBRE_DATE_ADHESION',
                                                            'MEMBRE_DUREE_ADHESION'
                                                        ], // only these field will be added in the step, rest all will be hidden/ignored.
                                                    ]
                                                ],
                                            ]
                                        ]);
                                        ?>`

All the fields appear in my form except the 'MEMBRE_SEXE and 'MEMBRE_DATE_DE_NAISSANCE fields that I tried to customize. Can you help me please? Thank you in advance.

**Comment by buttflattery** [comment]
Please format the code i cant understand a thing in it.

**Comment by hilmata** [comment]
Ah! sorry! that's my code 

``` php
 <?=
                                        FormWizard::widget([
                                            'formOptions' => [
                                                'id' => 'my_form_ajax',
                                                'enableClientValidation' => true,
                                                'enableAjaxValidation' => false,
                                            ],
                                            'theme' => FormWizard::THEME_DOTS,
                                            'enablePreview' => true,
                                            'classListGroup' => 'list-group',
                                            'classListGroupHeading' => 'list-group-heading',
                                            'classListGroupItem' => 'list-group-item-info',
                                            'classListGroupBadge' => 'danger',
                                            'steps' => [
//
                                                [
                                                    'model' => $model,
                                                    'title' => 'Identité',
                                                    'description' => 'identité du membre',
                                                    'formInfoText' => 'Renseignez l\'identité du membre',
                                                    'fieldConfig' => [
                                                        'only' => [
                                                            'BASE_ID',
                                                            'MEMBRE_NOM',
                                                            'MEMBRE_PRENOM',
                                                            'MEMBRE_SEXE' => [
                                                                'options' => [
                                                                    'type' => 'dropdown',
                                                                    'itemsList' => ['M' => 'Masculin', 'F' => 'Féminin'],
                                                                    'prompt' => 'Sélectionnez le sexe',
                                                                ],
                                                            ],
                                                            'MEMBRE_DATE_DE_NAISSANCE' => [
                                                                'widget' => DatePicker::class,
                                                                'options' => [
                                                                    'language' => 'es',
                                                                    'readonly' => true,
                                                                    'pluginOptions' => [
                                                                        'autoclose' => true,
                                                                        'format' => 'dd/mm/yyyy',
                                                                        'todayHighlight' => true,
                                                                    ]
                                                                ]
                                                            ],
                                                            'MEMBRE_LIEU_DE_NAISSANCE',
                                                            'MEMBRE_PROFESSION',
                                                            'MEMBRE_CONTACT',
                                                        ], // only these field will be added in the step, rest all will be hidden/ignored.
                                                    ]
                                                ],
                                                [
                                                    'model' => $model,
                                                    'title' => 'Sacrements',
                                                    'description' => 'Sacrements reçus par le membre',
                                                    'formInfoText' => 'Renseignez les sacrements reçus par le membre',
                                                    'fieldConfig' => [
                                                        'only' => [
                                                            'MEMBRE_DATE_DE_BAPTEME',
                                                            'MEMBRE_LIEU_DE_BAPTEME',
                                                            'MEMBRE_DATE_DE_COMMUNION',
                                                            'MEMBRE_LIEU_DE_COMMUNION',
                                                            'MEMBRE_DATE_DE_CONFIRMATION',
                                                            'MEMBRE_LIEU_DE_CONFIRMATION',
                                                            'MEMBRE_DATE_DE_MARIAGE',
                                                            'MEMBRE_LIEU_DE_MARIAGE',
                                                        ], // only these field will be added in the step, rest all will be hidden/ignored.
                                                    ]
                                                ],
                                                [
                                                    'model' => $model,
                                                    'title' => 'A propos du Sacré-Coeur',
                                                    'description' => 'Cérémonies reçus par le membre',
                                                    'formInfoText' => 'Renseignez les cérémonies reçus par le membre',
                                                    'fieldConfig' => [
                                                        'only' => [
                                                            'MEMBRE_DATE_INTRONISATION',
                                                            'MEMBRE_DATE_ADMISSION_SOLLENELLE',
                                                        ], // only these field will be added in the step, rest all will be hidden/ignored.
                                                    ]
                                                ],
                                                [
                                                    'model' => $model,
                                                    'title' => 'Associations',
                                                    'description' => 'Autres associations',
                                                    'formInfoText' => 'Renseignez les autres associations dans lesquelles le membre est actif',
                                                    'fieldConfig' => [
                                                        'only' => [
                                                            'MEMBRE_ASSOCIATION1',
                                                            'MEMBRE_ROLE_ASSOCIATION1',
                                                            'MEMBRE_ASSOCIATION2',
                                                            'MEMBRE_ROLE_ASSOCIATION2',
                                                        ], // only these field will be added in the step, rest all will be hidden/ignored.
                                                    ]
                                                ],
                                                [
                                                    'model' => $model,
                                                    'title' => 'Divers',
                                                    'description' => 'Autres informations',
                                                    'formInfoText' => 'Renseignez les autres informations',
                                                    'fieldConfig' => [
                                                        'only' => [
                                                            'MEMBRE_MOTIF_ADHESION',
                                                            'MEMBRE_OBJECTIFS_A_COURS_TERME',
                                                            'MEMBRE_OBJECTIFS_A_LONG_TERME',
                                                            'MEMBRE_ROLE_ASSOCIATION2',
                                                            'MEMBRE_DATE_ADHESION',
                                                            'MEMBRE_DUREE_ADHESION'
                                                        ], // only these field will be added in the step, rest all will be hidden/ignored.
                                                    ]
                                                ],
                                            ]
                                        ]);
                                        ?>
```

> 
> 
> Please format the code i cant understand a thing in it.

**Comment by buttflattery** [comment]
You are doing it wrong , you are providing the options for the `fieldConfig` under the `only` option. The `only` option takes only a list of the model fields that need to be populated, for customizing the fields you should provide the settings under the `fieldConfig`  see the code below where i fixed the first step to provide the customized layout for the input fields


```php
<?php echo
    FormWizard::widget([
        'formOptions' => [
            'id' => 'my_form_ajax',
            'enableClientValidation' => true,
            'enableAjaxValidation' => false,
        ],
        'theme' => FormWizard::THEME_DOTS,
        'enablePreview' => true,
        'classListGroup' => 'list-group',
        'classListGroupHeading' => 'list-group-heading',
        'classListGroupItem' => 'list-group-item-info',
        'classListGroupBadge' => 'danger',
        'steps' => [
            [
                'model' => $model,
                'title' => 'Identité',
                'description' => 'identité du membre',
                'formInfoText' => 'Renseignez l\'identité du membre',
                'fieldConfig' => [
                    'only' => [
                        'BASE_ID',
                        'MEMBRE_NOM',
                        'MEMBRE_PRENOM',
                        'MEMBRE_SEXE',
                        'MEMBRE_DATE_DE_NAISSANCE',
                        'MEMBRE_LIEU_DE_NAISSANCE',
                        'MEMBRE_PROFESSION',
                        'MEMBRE_CONTACT',
                    ], // only these field will be added in the step, rest all will be hidden/ignored.
                    'MEMBRE_SEXE' => [
                        'options' => [
                            'type' => 'dropdown',
                            'itemsList' => ['M' => 'Masculin', 'F' => 'Féminin'],
                            'prompt' => 'Sélectionnez le sexe',
                        ],
                    ],
                    'MEMBRE_DATE_DE_NAISSANCE' => [
                        'widget' => DatePicker::class,
                        'options' => [
                            'language' => 'es',
                            'readonly' => true,
                            'pluginOptions' => [
                                'autoclose' => true,
                                'format' => 'dd/mm/yyyy',
                                'todayHighlight' => true,
                            ],
                        ],
                    ],
                ],
            ],
            [
                'model' => $model,
                'title' => 'Sacrements',
                'description' => 'Sacrements reçus par le membre',
                'formInfoText' => 'Renseignez les sacrements reçus par le membre',
                'fieldConfig' => [
                    'only' => [
                        'MEMBRE_DATE_DE_BAPTEME',
                        'MEMBRE_LIEU_DE_BAPTEME',
                        'MEMBRE_DATE_DE_COMMUNION',
                        'MEMBRE_LIEU_DE_COMMUNION',
                        'MEMBRE_DATE_DE_CONFIRMATION',
                        'MEMBRE_LIEU_DE_CONFIRMATION',
                        'MEMBRE_DATE_DE_MARIAGE',
                        'MEMBRE_LIEU_DE_MARIAGE',
                    ], // only these field will be added in the step, rest all will be hidden/ignored.
                ],
            ],
            [
                'model' => $model,
                'title' => 'A propos du Sacré-Coeur',
                'description' => 'Cérémonies reçus par le membre',
                'formInfoText' => 'Renseignez les cérémonies reçus par le membre',
                'fieldConfig' => [
                    'only' => [
                        'MEMBRE_DATE_INTRONISATION',
                        'MEMBRE_DATE_ADMISSION_SOLLENELLE',
                    ], // only these field will be added in the step, rest all will be hidden/ignored.
                ],
            ],
            [
                'model' => $model,
                'title' => 'Associations',
                'description' => 'Autres associations',
                'formInfoText' => 'Renseignez les autres associations dans lesquelles le membre est actif',
                'fieldConfig' => [
                    'only' => [
                        'MEMBRE_ASSOCIATION1',
                        'MEMBRE_ROLE_ASSOCIATION1',
                        'MEMBRE_ASSOCIATION2',
                        'MEMBRE_ROLE_ASSOCIATION2',
                    ], // only these field will be added in the step, rest all will be hidden/ignored.
                ],
            ],
            [
                'model' => $model,
                'title' => 'Divers',
                'description' => 'Autres informations',
                'formInfoText' => 'Renseignez les autres informations',
                'fieldConfig' => [
                    'only' => [
                        'MEMBRE_MOTIF_ADHESION',
                        'MEMBRE_OBJECTIFS_A_COURS_TERME',
                        'MEMBRE_OBJECTIFS_A_LONG_TERME',
                        'MEMBRE_ROLE_ASSOCIATION2',
                        'MEMBRE_DATE_ADHESION',
                        'MEMBRE_DUREE_ADHESION',
                    ], // only these field will be added in the step, rest all will be hidden/ignored.
                ],
            ],
        ],
]);
?>
```

**Comment by hilmata** [comment]
Thanks a lot.It work for me. And sorry for my bad english.

**Comment by buttflattery** [comment]
You are welcome @hilmata , in future please use stackoverflow for questions and use the [yii2-formwizard](https://stackoverflow.com/questions/tagged/yii2-formwizard) and `yii2` tags so that i am notified too. Good luck.
