### ISSUE TITLE
Separator and custom label 

### ISSUE THREAD

**Issue by buttflattery** [buttflattery/yii2-formwizard#55]
In the preview step  when a field has no value selected or filled, it’s show “NA”.

- Is it possible to choose another text to display instead of “NA”?
- For a tabular step, also, is it possible to insert a separator line between tabular models?

**Comment by buttflattery** [comment]
The separator support is already there and you can override the following class by modifying the `border-top` to `5px`.

```
.sw-main .fields_container .tabular-row {
    margin-top: 10px;
    border-top: 1px solid #c8c8c8;
    padding: 5px;
    width: 80%;
}
```
and you can use the `previewEmptyText` option in the formwizard to set the custom text.

```
echo FormWizard::widget(
    [
        'wizardContainerId' => 'my-id',
        'previewEmptyText' => 'Not Available',
        'steps' => [
        ]
]);
```

**Comment by mondomeme** [comment]
Thank you for updating the repository.

For the tabular step I noticed in the preview step the data coming drom tabular step must be separated for each model added.  
The image below shows the problem:
![immagine](https://user-images.githubusercontent.com/38080084/75136659-a4c38d00-56e5-11ea-95c5-7b4ef61ebd55.png)
the red arrow indicated where I think it should be a separator line.

**Comment by buttflattery** [comment]
Umm . the separator was for the tabular step itself not the data in the preview step. You can add another issue and i will add it to the working queue. @mondomeme

**Comment by mondomeme** [comment]
There is the related new [issue](https://github.com/buttflattery/yii2-formwizard/issues/58). @buttflattery
