### ISSUE TITLE
fieldOrder doesn't work for multiple models

### ISSUE THREAD

**Issue by mondomeme** [buttflattery/yii2-formwizard#56]
I'm using yii2-formwizard and I have two different models (model1 and model2) in the same step. I use the  following `fieldConfig`:  
`fieldConfig=>['email', 'phone_1', 'phone_2', 'fax', 'profession_id', 
            'hobby_id', 'sport_id','notes']`, 
where` 'email', 'phone_1', 'phone_2' ,'notes'` are model1 fields, the others are model2 fields instead.
 The result is: 
![immagine](https://user-images.githubusercontent.com/38080084/74825814-d665de00-530a-11ea-9d3a-1fbf58f33d65.png). 

As you can see, the `fieldOrder `not is applied for multiple model.

**Comment by buttflattery** [comment]
Hmm, the way image shows it looks like it is not ordering according to the `fieldConfig`, i might have to test it and will update the code after i fix it, meanwhile you can use the `fieldOrder` to order the fields and check if it works, i am currently in office at the moment and cant check, will update you once i get back.

**Comment by buttflattery** [comment]
@mondomeme hello i just pushed the changes to the master branch please run the composer update on you project to get the latest changes and try now, it should work correctly with multiple models steps too.

**Comment by mondomeme** [comment]
@buttflattery thank you for the update! It seems to work properly, but when the field form input is a select2, if I don't select any value in the preview step it show the placeholder (if set): 

![immagine](https://user-images.githubusercontent.com/38080084/75138831-78127400-56eb-11ea-92e2-e9131dc5fa2b.png)

**Comment by mondomeme** [comment]
Thank you! It seems to works properly!

**Comment by mondomeme** [comment]
@buttflattery I have updated the wizard to the latest version and the fieldOrder for multiple models doesn't work

**Comment by buttflattery** [comment]
I did some enhancements related to the function abstraction, maybe it was effected by it, i will check and then reply soon.

**Comment by buttflattery** [comment]
Should be fixed now, please run `composer update` @mondomeme

**Comment by mondomeme** [comment]
@buttflattery thank you, now it is fixed
