### ISSUE TITLE
Preview step separator line for tabular step data

### ISSUE THREAD

**Issue by mondomeme** [buttflattery/yii2-formwizard#58]
For the tabular step I noticed in the preview step the data coming from tabular step must be separated for each model added.
The image below shows the problem:

![immagine](https://user-images.githubusercontent.com/38080084/75137415-d6d5ee80-56e7-11ea-88ba-ba31a4068818.png)

 the red arrow indicated where I think it should be a separator line.

**Comment by buttflattery** [comment]
@mondomeme this should be fixed in 7e9e7ec please verify and close the issue

**Comment by mondomeme** [comment]
Thank you for the update! I tried it and it works very well
