### ISSUE TITLE
Preview step: select2 empty field showing placeholder

### ISSUE THREAD

**Issue by mondomeme** [buttflattery/yii2-formwizard#59]
After the update related to the [issue](https://github.com/buttflattery/yii2-formwizard/issues/55), I noticed the followiing: 

if there are empty data related to form field input implemented as select2, in the preview step these fields are not display with the `previewEmptyText ` option value, but with the select2 placeholder : 
![immagine](https://user-images.githubusercontent.com/38080084/75139651-76e24680-56ed-11ea-8bf9-b36cf2ace15a.png)

**Comment by buttflattery** [comment]
Yes you are right the select2 portions were missed i will update them today.

**Comment by buttflattery** [comment]
This should be fixed with f1bbc6a @mondomeme , please pull the latest changes and verify if all is good.

**Comment by mondomeme** [comment]
@buttflattery I tried it now and it works. Thank you!
