### ISSUE TITLE
Request: Visability flag

### ISSUE THREAD

**Issue by thomassb** [buttflattery/yii2-formwizard#6]
Can we please have a visibility variable in the field config?

`isset($fieldConfig[$attribute]['visible'])&& $fieldConfig[$attribute]['visible'] == false`

**Comment by buttflattery** [comment]
ummm... @thomassb  can you please add some scenario where it is needed and cant be done using the currently available options, a use case will help.

**Comment by buttflattery** [comment]
ok, but dont you think you can use the `except` or `only` option for such cases?
