### ISSUE TITLE
Preview step: hidden input field should be hidden

### ISSUE THREAD

**Issue by mondomeme** [buttflattery/yii2-formwizard#62]
I have a step with a form hidden input, which value is set upon the occurance of an event. In the preview step this field should be hidden instead of be shown.

**Comment by buttflattery** [comment]
Yes it should be technically hidden which wasnt covered in the code, will update it shortly.

**Comment by buttflattery** [comment]
@mondomeme Please pull the latest code by running `composer update` and clear your assets directory and then refresh , this is added via ec6402b

**Comment by mondomeme** [comment]
I'm sorry if I respond only now, but it doesn't work for me. I deleted my assets directory and cache and the input hidden field has the following `options` : ` 'options' => [
                            'id' => 'loaded-files-list',
                            'type' => 'hidden'
                        ]` .

**Comment by buttflattery** [comment]
@mondomeme did you pull the latest code by running `composer update` ? compare the loaded script file with the line https://github.com/buttflattery/yii2-formwizard/blob/master/src/assets/js/formwizard.js#L212 it is working correctly, 

Try adding the following config under the `components` in your config file and press CTRL+F5 and then verify ,

```
'assetManager'=>[
    'forceCopy'=>true,
]
```

you can remove this afterwards.

**Comment by mondomeme** [comment]
@buttflattery yes I pulled the code and the line 212 is the same.  I have the suggested config under the `components` in my config file.

**Comment by buttflattery** [comment]
Cant say much what you are doing wrong with watching the code but for me it works correctly, I just checked it with the following config for the field. @mondomeme 

```
'description' => [
    'options' => [
        'type' => 'hidden',
    ],
],
```

**Comment by mondomeme** [comment]
The problem is the fact I have set the `id` option for the field. I set this field value on kartik fileinput `filedeleted` event accessing on it by field id. If I removed this option, the field now is hidden in the preview step.

**Comment by buttflattery** [comment]
Hmmm , that could be the reason becausethe plugin collects the field names baed on model generated id for the fields, you might have to remove the custom id and use the model generated id in your script

**Comment by mondomeme** [comment]
@buttflattery ok I did what you said and now it's ok
