### ISSUE TITLE
Customize form info text of preview step 

### ISSUE THREAD

**Issue by mondomeme** [buttflattery/yii2-formwizard#63]
I would like to customize the formInfoText for the preview step, i.e for example instead of  'Final Preview of all Steps' I want to see 'Preview Step'.

**Comment by buttflattery** [comment]
you can do this now read [here](https://github.com/buttflattery/yii2-formwizard#enablepreview-boolean-since-v120) @mondomeme

**Comment by mondomeme** [comment]
@buttflattery thank you, I searched on docs, but I didn't find it. Maybe I was searching on one of the previous version of the wizard

**Comment by buttflattery** [comment]
@mondomeme no it wasnt added on the README neither was supported but was added after you reported it.
