### ISSUE TITLE
Kartik datepicker/datecontrol fields : value not shown in preview

### ISSUE THREAD

**Issue by mondomeme** [buttflattery/yii2-formwizard#64]
I use for date fields the `kartik/DateControl` widget in my formwizard. In the preview steps these fields are not shown, but the values are stored in the database tables. 

Insert value for a date field by date control widget:
![image](https://user-images.githubusercontent.com/38080084/77344765-f4709500-6d33-11ea-8d6b-9470fa7a265a.png)

Field missing in the preview step
![image](https://user-images.githubusercontent.com/38080084/77344834-0d794600-6d34-11ea-95bd-22d0a0554c78.png)

**Comment by buttflattery** [comment]
as i mentioned in one of the previous issue https://github.com/buttflattery/yii2-formwizard/issues/61#issuecomment-593647694 that if your input and label does not follow the default expected layout the preview step wont be able to show as it requires the label and input both on the same level you have to override the getPreview() section and write your own implementation @mondomeme

**Comment by mondomeme** [comment]
@buttflattery I found the problem and I solved. It was in the `previewStep.add` function at [https://github.com/buttflattery/yii2-formwizard/blob/master/src/assets/js/formwizard.js#L212](url) .
The date picker field are hidden in the form, so I added a check for the fieldName.
