### ISSUE TITLE
Tabular dependent inputs issue

### ISSUE THREAD

**Issue by girishcp** [buttflattery/yii2-formwizard#66]
@buttflattery 
I am facing the issue with the yii2-formwizard since I have updated the new version with the latest features "Show hide Tabular dependent inputs".

When I am adding a second item (by add button) in the STEP_TYPE_TABULAR form then it's taking the same condition (depend) from the first item added and It's also disabled the drop-down fields in the second added item. 

For example,
I have 4 fields in the form, 2 are drop-down and 2 are textbox fields (hide by default when it's loaded). Each drop-down has a depend condition. 
In the first item added, I am selecting YES in both the drop-down and its showing the text fields as required. BUT when I am adding new items by clicking Add option then showing all the fields by default and drop-down options are disabled.

**Comment by buttflattery** [comment]
This should be fixed with ce1f7b2 pleasae pull the latest code by running `composer update` @girishcp
