### ISSUE TITLE
TabularEvents doesn't work after last update

### ISSUE THREAD

**Issue by mondomeme** [buttflattery/yii2-formwizard#67]
Before the last update, the `tabularEvents` option worked perfectly. I have checked this, because I have two version of my project, the first with the  updated formwizard, the latter without update.

**Comment by buttflattery** [comment]
can you check the version number for both of them it would show you the hash 
run `composer show -i` on terminal and add both the hashes shown @mondomeme

**Comment by mondomeme** [comment]
Updated (tabularEvent not working):
buttflattery/yii2-formwizard       dev-master a0a0880 

Not Updated (tabularEvent working):
buttflattery/yii2-formwizard       dev-master a0e9c2c

**Comment by buttflattery** [comment]
@mondomeme try switching the version to `1.7.2` by changing in your `composer.json` where it is not working, replace

`"buttflattery/yii2-formwizard": "@dev",`

with 

`"buttflattery/yii2-formwizard": "1.7.2",`

**Comment by buttflattery** [comment]
it might take some time to fix it as i am currently too much occupied, or you can look into the issue and submit a PR

**Comment by mondomeme** [comment]
@buttflattery I changed the version to 1.7.2, but it didn't work. I tried to run `composer update`  to 1.7.2 version, but there were other problems, resolved with newer versions.

**Comment by buttflattery** [comment]
alright i will look into this today @mondomeme

**Comment by buttflattery** [comment]
meanwhile can you paste the exception that is thrown when you update the composer @mondomeme

**Comment by mondomeme** [comment]
@buttflattery  the option `previewHeading` does not exist.

**Comment by buttflattery** [comment]
I thought you were saying about the error while running `composer update` seems like you are getting error while running the extension after reverting to that version? @mondomeme

**Comment by mondomeme** [comment]
I'm sorry if I was not clear, but the error us after reverting to 1.7.2 version

**Comment by buttflattery** [comment]
hey @mondomeme coming back to the problem, as you know the situation from the last month these days worldwide I could not give enough time to my personal widgets in open source, so what is the exact problem you are having with tabular inputs, if you were using the dependent inputs with the tabular step then i just pushed a fix for it  [here](https://github.com/buttflattery/yii2-formwizard/issues/67)

**Comment by claudiogg88** [comment]
hi after update last commit its not executing the tabular events

the jquery selector is wrong, the property $index in class tabular is null



           $stepIndex = $this->index;
           ...
           $this->_addTabularEvents($customFieldConfig, $modelIndex, $attributeId, $stepIndex);


(my tabular is the step 3)

html created:
("formwizard.afterClone", "#my_form_tabular #step- #proyectotipocapacit


thanks. sorry my english

**Comment by buttflattery** [comment]
@claudiogg88  can you add the actual exception message yo uare getiing

**Comment by buttflattery** [comment]
@claudiogg88  please run the `composer update` again you were right i missed the step index while initializing the tabular step class, good catch it should work correctly now

**Comment by claudiogg88** [comment]
there is no exception. 
when i press add button nothing happen 
no afterclone / beforeclone fuction is called

because  the selector is wrong 

 ("formwizard.afterClone", "#my_form_tabular **#step- #**proyectotipocapacit

empty number because the stepindex is null in your class tabular.php

        211: $stepIndex = $this->index;
         ...
         256:$this->_addTabularEvents($customFieldConfig, $modelIndex, $attributeId, $stepIndex);
...
322: $(document).on("formwizard.{$eventName}","#{$formId} #step-{$index} .fields_container>div[id^='row_']",{$eventCallBack});

**Comment by buttflattery** [comment]
@claudiogg88  i have pushed a hotfix 10c751c for it it should be fixed after you pull the latest code again using `composer update`

**Comment by claudiogg88** [comment]
its work!!! many thanks. excelent plugin!!

**Comment by buttflattery** [comment]
@claudiogg88 glad it works for you i was doing some enhancement on the plugin that involves function abstraction and all the fuss started there :P but i think it will get stable one the issues resolved and work better than before, please show some love by giving a star to the extension it helps the creator alot.

**Comment by buttflattery** [comment]
@mondomeme please close the issue after you verify the fix and if it works well. otherwise you can followup

**Comment by buttflattery** [comment]
closing this issue if you find any problems you can re-open it again.
