### ISSUE TITLE
Request: Feild Order

### ISSUE THREAD

**Issue by thomassb** [buttflattery/yii2-formwizard#7]
The order of fields are hard to control as the order is taken from the model attributes. I suggest an extra option called 'order' this would be an integer order.

**Comment by buttflattery** [comment]
i recently added an option `fieldOrder` under the steps option if you look into the [changelog](https://github.com/buttflattery/yii2-formwizard/blob/master/ChangeLog.md)

example code could be like 

```
'steps' => [
        [
            'model' => $modelShoots,
            'title' => 'My Shoots',
            'description' => 'Add your shoots',
            'formInfoText' => 'Add all fields',
            'fieldOrder' => ['name', 'shoot_type', 'description'],
           
        ],
```

for details you can look [here](https://github.com/buttflattery/yii2-formwizard/blob/master/src/FormWizard.php#L391)

**Comment by thomassb** [comment]
Fantastic, I was looking at a previous build so missed this.

**Comment by buttflattery** [comment]
No problem @thomassb there would be lots of things that would need to be updated and as soon as they come to mind or are raised by someone else i fix it asap.

**Comment by buttflattery** [comment]
you can add the repo to watch list to be aware of the changes or additions
