### ISSUE TITLE
Unable to Access Website Demo 

### ISSUE THREAD

**Issue by Vesals** [buttflattery/yii2-formwizard#70]
Around 2 weeks from when I posted this, the demo is still accesible. When I want to look it up again as reference for my assignment project, I cannot access it. Can you please open the access again, thank you very much.

![image](https://user-images.githubusercontent.com/61060248/82919800-b0527880-9fa0-11ea-942d-59ce7ca0f580.png)

**Comment by buttflattery** [comment]
@Vesals I didnt revoked access to any of the demos but looks like there is a problem since morning with the hosting i have created a ticket will be resolved soon, meanwhile you can look into the wiki docs  https://github.com/buttflattery/yii2-formwizard/wiki

**Comment by buttflattery** [comment]
@Vesals the demos are up and working now

**Comment by Vesals** [comment]
thank you very much! ☺

**Comment by buttflattery** [comment]
@Vesals  you are welcome.
