### ISSUE TITLE
Select2+DepDrop With Tabular Input and Tabular Event

### ISSUE THREAD

**Issue by Vesals** [buttflattery/yii2-formwizard#71]
Hello, I want to implement the Select2+DepDrop function in my project, I have multiple array form that uses DepDrop. The first form is working properly, the option **CO_NAMA** changes depends on what I chose on **CO_ID**. But the second array form doesn't change depending on what I choose because it still depending on the first form value. Do you have the solution for this problem?

`<?php
	$model2 = [new KermaPerusahaan()];
	$model3 = [new KermaStatus()];

	echo FormWizard::widget([
		'formOptions' => [
		    'id' => 'my_form_multi_model_single_step',
		],
		'theme' => FormWizard::THEME_DOTS,
		'enablePreview'=>true,
	    'classListGroup' => 'list-group',
	    'classListGroupHeading' => 'list-group-heading',
	    'classListGroupItem' => 'list-group-item-info',
	    'classListGroupBadge' => 'danger',
		'steps' => [
     	   [
		        'model' => $model2,
		        'type' => FormWizard::STEP_TYPE_TABULAR,
		        'title' => 'My Shoots 4',
		        'fieldConfig' => [
                	'CO_ID' => [
                		'widget' => Select2::class,
	                    'containerOptions' => [
	                        'class' => 'form-group',
	                        // 'id' => 'CO_ID'
	                    ],
	                    'options' => [
	                        'data' => ArrayHelper::map(KermaPerusahaan::find()->all(),'CO_ID','CO_ID'),
	                        'options' => [
	                            'class' => 'form-control',
	                            // 'id' => 'kermaperusahaan'
	                        ],

	                        // 'theme' => Select2::THEME_BOOTSTRAP,
	                        'pluginOptions' => [
	                            'allowClear' => true,
	                            'placeholder' => 'Select'
	                        ]
	                    ],
	                    'tabularEvents' => [
						'beforeClone' => "function(event, params){
                                //fix for select2 destroy the plugin

                                let element = $(this);
                                element.select2('destroy');
                            }",
                            "afterClone" => "function(event, params){
                                //bind select2 again after clone

                                let element = $(this);
                                let elementId = $(this).attr('id');
                                let dataKrajee = eval(element.data('krajee-select2'));
                                let dataSelect2Options = element.data('s2-options');
                                $.when(element.select2(dataKrajee)).done(initS2Loading(elementId, dataSelect2Options));
                            }",
                         "afterInsert" => "function(event,params){
                                let selectElement = $(this).find('.field-kermaperusahaan-'+params.rowIndex+'-co_id > select');
                                let dataKrajee = eval(selectElement.data('krajee-select2'));

                                //update the dataset attribute to the
                                if (typeof selectElement[0].dataset.select2Id !== 'undefined') {
    
                                    //get the old dataset which has the old id of the input the select2 is bind to 
                                    let oldDataSelect2Id = selectElement[0].dataset.select2Id;
    
                                    //delete the old dataset
                                    delete selectElement[0].dataset.select2Id;
    
                                    //add the new dataselect pointing to the new id of the cloned element
                                    let newDataSelect2Id = oldDataSelect2Id.replace(
                                          /\-([\d]+)\-/,
                                          '-' + parseInt(params.rowIndex) + '-'
                                    );

                                    //add the new dataset with the new cloned input id 
                                    selectElement[0].dataset.select2Id= newDataSelect2Id;
                                }
                                selectElement.select2(dataKrajee);
                            }"
                    	]
	                ],

	                'CO_NAMA' => [
		                'widget' => DepDrop::classname(),
	                    'options'=>[
	                        'type' => DepDrop::TYPE_SELECT2,
	                        'options'=>[
	                            'placeholder' => 'Select ...'
	                        ],
	                        'select2Options' => [
	                        	'pluginOptions' => [
	                        		'allowClear' => true
	                        	]
                        	],
	                        'pluginOptions'=>[
						        'depends'=>[ 'kermaperusahaan-0-co_id' ],
        						'placeholder'=>'Select...',
						        'url'=>Url::to(['/site/branches'])
						    ]
						],
						'tabularEvents' => [
						'beforeClone' => "function(event, params){
                                //fix for select2 destroy the plugin

                                let element = $(this);
                                element.select2('destroy');
                            }",
                            "afterClone" => "function(event, params){
                                //bind select2 again after clone

                                let element = $(this);
                                let elementId = $(this).attr('id');
                                let dataKrajee = eval(element.data('krajee-select2'));
                                let dataSelect2Options = element.data('s2-options');
                                $.when(element.select2(dataKrajee)).done(initS2Loading(elementId, dataSelect2Options));
                            }",
                         "afterInsert" => "function(event,params){
                                let selectElement = $(this).find('.field-kermaperusahaan-'+params.rowIndex+'-co_nama > select');
                                let dataKrajee = eval(selectElement.data('krajee-select2'));

                                //update the dataset attribute to the
                                if (typeof selectElement[0].dataset.select2Id !== 'undefined') {
    
                                    //get the old dataset which has the old id of the input the select2 is bind to 
                                    let oldDataSelect2Id = selectElement[0].dataset.select2Id;
    
                                    //delete the old dataset
                                    delete selectElement[0].dataset.select2Id;
    
                                    //add the new dataselect pointing to the new id of the cloned element
                                    let newDataSelect2Id = oldDataSelect2Id.replace(
                                          /\-([\d]+)\-/,
                                          '-' + parseInt(params.rowIndex) + '-'
                                    );

                                    //add the new dataset with the new cloned input id 
                                    selectElement[0].dataset.select2Id= newDataSelect2Id;
                                }
                                selectElement.select2(dataKrajee);
                            }"
                    	] //end tabular 2
		            ],
	     	   ]
			],
		]
	]);

?>`

Screenshot: 
First Form:
![image](https://user-images.githubusercontent.com/61060248/83162798-731eef80-a134-11ea-98dc-065c5f4cb8ee.png)

After Add:
![image](https://user-images.githubusercontent.com/61060248/83163011-b24d4080-a134-11ea-806e-e63667c11e61.png)

**Comment by buttflattery** [comment]
You should go through the wiki docs for working with the 3rd party widgets, this is not related to the forwizard but the users will have to find a workaround for them like i have described int his article https://github.com/buttflattery/yii2-formwizard/wiki/Tabular-Steps:-Working-with-3rd-Party-Widgets
