### ISSUE TITLE
Repeating form fields using loop

### ISSUE THREAD

**Issue by zulsan88** [buttflattery/yii2-formwizard#74]
Hi,

Any ways to create multiple form field depending on the looping count? Or it is possible to create custom field without Model?

I've tried to search from https://github.com/buttflattery/yii2-formwizard/wiki. Nothing can do with my issue. Also tried tabular, but it is different from what I want to do.

From what I do, it only able to show one question. When inserting array value, error : **Argument 1 passed to buttflattery\formwizard\step\Sorter::getStepFields() must be an instance of yii\base\Model, array given, called in C:\xampp\htdocs\awc\vendor\buttflattery\yii2-formwizard\src\step\Sorter.php on line 42** occur

![awc](https://user-images.githubusercontent.com/64367844/87777329-ddfac600-c85b-11ea-93a6-32b209e436ee.png)

Thank you.

**Comment by buttflattery** [comment]
not clear what you are asking, might be helpful if you add the code along that you are using @zulsan88 , and i can figure what you are trying to do and if it is possible to do or not.
