### ISSUE TITLE
Add option for setting label of Add button

### ISSUE THREAD

**Issue by amoracr** [buttflattery/yii2-formwizard#76]
Hello. I am using your extension and it is very helpful for creating a wizards for different forms. Right now I have a little issue with the extension. The issue is that I can not set a custom label for the Add button.  I can use custom labels for Previous, Next and Finish buttons, and even I can change the icon itself, but I can not do that with the label.

I would like to have an option for setting the label of the Add button, in the same way that you can set the label for previous, next or finish buttons.

**Comment by buttflattery** [comment]
Just added an option to add the label for the add button 7b7942f5555d528cd46c5dbc55de71b076bcfca5, you can use the `labelAddRow` in the main options to set the label for the button @amoracr , update you code by running `composer update`
