### ISSUE TITLE
show the step based on the value of an attribute

### ISSUE THREAD

**Issue by paskuale75** [buttflattery/yii2-formwizard#77]
**Is your feature request related to a problem? Please describe.**
I've a model, with an attribute called 'type_id' , switch on this attribute I want show a correct step to user.

**Describe the solution you'd like**
I don't know ...
**Describe alternatives you've considered**

**Additional context**

**Comment by buttflattery** [comment]
not getting correctly what you are saying, do yo umean you have a switch input configure with the `type_id` field and you want to go to a specific step when you select it ? @paskuale75

**Comment by paskuale75** [comment]
> not getting correctly what you are saying, do yo umean you have a switch input configure with the `type_id` field and you want to go to a specific step when you select it ? @paskuale75

Yes

**Comment by buttflattery** [comment]
well this is something related to smartwizard js library and not something that this widget covers you need to use javascript to do that and i think you can find an example to switch to a particular step if you enable the preview step, and look into it , if you click any label in the preview step it will navigate you to the step that field belongs to , you can look into the formwizard.js file where i am doing that https://github.com/buttflattery/yii2-formwizard/blob/master/src/assets/js/formwizard.js#L236 hope it helps @paskuale75
