### ISSUE TITLE
Next Field list are based from previous field Selection 

### ISSUE THREAD

**Issue by moysoft** [buttflattery/yii2-formwizard#83]
For example, I have 2 Fields, the first field is a dropdown for phone manufacturer let say "Apple, Samsung", the second field is also a dropdown and data collected from the database based on  first user selection, for example, if the user pick Apple then the second dropdown queried the database based on "Apple" string and dropdown list many kinds of Apple model (iPhone 4, 5, etc), if user select "Samsung" for the first selection and the second dropdown list many kinds of Samsung device (Galaxy S7, Galaxy Note 10, etc).

**Comment by buttflattery** [comment]
sorry @moysoft but reading your issue it looks like your issue is related to the dropdowns and not the formwizard widget? you can use the Select2 Dependent dropdown for your use case.

**Comment by moysoft** [comment]
Yes, but for dependent dropdown **it's depend on first component's id**  (dependent component). When I add **id** to the first component, the summary page for first component and the second component are **undefined**.

**Comment by moysoft** [comment]
Please fix this bug. Thankyou

**Comment by moysoft** [comment]
After lookup from page source finally I found the id is automatically set to "dynamic"+component name, in this case id are "dynamic-jenis_katalog" and "dynamic-id_periode" respectively. _**No need**_ to add **component **id**** manually.

Thank you for good and use full component.
