### ISSUE TITLE
Objects parameters in options of an inner widget

### ISSUE THREAD

**Issue by vitalypark0555** [buttflattery/yii2-formwizard#9]
Hello, I really liked your wrapper of smart wizard, however, I can't put object variables into 'options' when I use another widget inside of your one. I think it's important, cuz many other widgets require setting object variables into options array. Thanks beforehand.

```
[
    'model' => $hiringTeam,
    'title' => 'HIRING TEAM',
    'description' => 'Choose members of the selection committee',
    'formInfoText' => '',
    'fieldConfig' => [
        'only' => ['employee_ids'],
        'employee_ids' => [
            'widget' => \softark\duallistbox\DualListbox::className(),
            'options' => [
                'model' => $hiringTeam,
                'attribute' => $hiringTeam->employee_ids,
                'items' => $employees,
                'clientOptions' => [
                    'moveOnSelect' => true,
                    'selectedListLabel' => 'General Hiring Team',
                    'nonSelectedListLabel' => 'Hiring Team for this job',
                ],
            ],
        ],
    ],
],
```

**Comment by buttflattery** [comment]
Hello, are you talking about passing the `$model` to the widget you are using? if that is so you dont need to pass it as the formwizard uses `ActiveForm` and the model passed for the step will be used for the widget as in the example for using the `DualListbox` [here](https://github.com/softark/yii2-dual-listbox) with the ActiveForm is like below 

```
echo $form->field($model, $attribute)->widget(DualListbox::className(),[
        'items' => $items,
        'options' => $options,
        'clientOptions' => [
            'moveOnSelect' => false,
            'selectedListLabel' => 'Selected Items',
            'nonSelectedListLabel' => 'Available Items',
        ],
    ]);
```
and the FormWizard Plugin does the starting part itself which is 

`echo $form->field($model, $attribute)`

and the `wiget` and the `options` that you pass are then linked with the field using 

`->widget($widget,$options)`

so you should pass them like

```
[
    'model' => $hiringTeam,
    'title' => 'HIRING TEAM',
    'description' => 'Choose members of the selection committee',
    'formInfoText' => '',
    'fieldConfig' => [
        'only' => ['employee_ids'],
        'employee_ids' => [
            'widget' => \softark\duallistbox\DualListbox::className(),
            'options' => [
                'items' => $employees,
                'clientOptions' => [
                    'moveOnSelect' => true,
                    'selectedListLabel' => 'General Hiring Team',
                    'nonSelectedListLabel' => 'Hiring Team for this job',
                ],
            ],
        ],
    ],
],
```

**Comment by vitalypark0555** [comment]
Hi **buttflattery**. Thanks for your response. I have tried different options, but nothing works. 
I get error "htmlspecialchars() expects parameter 1 to be string, object given".

**Comment by buttflattery** [comment]
@vitalypark0555 it does work correctly without any problem see the image i get the following 

![image](https://user-images.githubusercontent.com/1536454/50366071-72764700-0599-11e9-88b0-8277c84fd6be.png)

when i use this config

```
'fieldConfig' => [
    'only' => ['tag_id'],
    'tag_id' => [
        'widget' => \softark\duallistbox\DualListbox::class,
        'options' => [
            'items' => ArrayHelper::map(Tags::find()->all(), 'id', 'name'),
            'clientOptions' => [
                'moveOnSelect' => true,
                'selectedListLabel' => 'General Hiring Team',
                'nonSelectedListLabel' => 'Hiring Team for this job'
            ]
        ]
    ]
]
```

You need to look into your `items` option for the `DualListbox` that you are passing you should pass them in `key=>value` pair. The array keys are option values, and the array values are the corresponding option labels.

**Comment by vitalypark0555** [comment]
**Buttflattery**, thank you very much. It works like a charm.

**Comment by buttflattery** [comment]
@vitalypark0555 no problem you are welcome.

**Comment by buttflattery** [comment]
do leave a STAR  if you like the extension @vitalypark0555

**Comment by vitalypark0555** [comment]
Done!
